### Word Embedding Techniques using Embedding Layer in Keras

In [39]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'This is Anil',
     'I belong to tirupathi',
     'I am quite good in python programming langauge ',
    'I am a good boy',
     'I am a good developer',
     'I am carrying an 2 years of experience ',
     'my hobbies are playing cricket',]

In [3]:
sent

['This is Anil',
 'I belong to tirupathi',
 'I am quite good in python programming langauge ',
 'I am a good boy',
 'I am a good developer',
 'I am carrying an 2 years of experience ',
 'my hobbies are playing cricket']

In [4]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr) ## observe the printed array indexes....in the above sentences  I word have some index i,e 3299 which is also same for remaining indexes also

[[5388, 6597, 7854], [3229, 1088, 7890, 7855], [3229, 9601, 3570, 8203, 8167, 7466, 5112, 1866], [3229, 9601, 7948, 8203, 4407], [3229, 9601, 7948, 8203, 5639], [3229, 9601, 4362, 1770, 3889, 5863, 3132, 7250], [9257, 7230, 506, 6251, 9961]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0    0 5388 6597 7854]
 [   0    0    0    0    0    0 3229 1088 7890 7855]
 [   0    0 3229 9601 3570 8203 8167 7466 5112 1866]
 [   0    0    0    0    0 3229 9601 7948 8203 4407]
 [   0    0    0    0    0 3229 9601 7948 8203 5639]
 [   0    0 3229 9601 4362 1770 3889 5863 3132 7250]
 [   0    0    0    0    0 9257 7230  506 6251 9961]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 10)            100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237
   -0.01451647  0.02145778 -0.04161109 -0.00558824  0.0210628 ]
  [ 0.02863203 -0.00839419  0.03937136  0.01761321  0.04558423
    0.03279387  0.0427067   0.03792958  0.039086

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0, 5388, 6597, 7854])

In [16]:
print(model.predict(embedded_docs)[0])

[[ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.0159135  -0.01272943 -0.03590375 -0.01901863 -0.00036237 -0.01451647
   0.02145778 -0.04161109 -0.00558824  0.0210628 ]
 [ 0.02863203 -0.00839419  0.03937136  0.01761321  0.04558423  0.03279387
   0.0427067   0.03792958  0.03908631 -0.00211947]
